#!/usr/bin/perl -w

# Construct cityinfo.h from zone.tag
# (c)2005-2012 Kevin Boone

use strict;

open IN,"</usr/share/zoneinfo/zone.tab" or die "Can't open zone.tab";
open OUT,">src/cityinfo.h" or die "Can't write cityinfo.h";
print OUT "//Do not edit this file by hand\n";
print OUT "static SolCity cities[] = {\n";

while (my $line=<IN>)
  {
  chomp ($line);
  if ($line =~ /^#/) { next; }
  $line =~ /([A-Z][A-Z])\s+([0-9+-]+)\s+([-a-zA-Z\/_]+)/;
  my $country = $1;
  my $latlong= $2;
  my $name= $3;
  $latlong =~ /([+-])([0-9]+)([+-])([0-9]+)/;
  my $lat_sign = $1;
  my $lat = $2;
  my $long_sign = $3;
  my $long = $4;
  $lat =~ /([0-9][0-9])([0-9][0-9])/;
  my $lat_deg = $1;
  my $lat_min = $2;
  $long =~ /([0-9][0-9][0-9])([0-9][0-9])/;
  my $long_deg = $1;
  my $long_min = $2;
  $lat_deg =~ s/^0//;
  $lat_min =~ s/^0//;
  $long_deg =~ s/^0//;
  $long_deg =~ s/^0//;
  $long_min =~ s/^0//;

  my $lati = $lat_deg + $lat_min / 60.0;
  my $longt = $long_deg + $long_min / 60.0;
  if ($lat_sign eq "-") { $lati = -$lati; }
  if ($long_sign eq "-") { $longt = -$longt; }
  print OUT "{";
  print OUT "\"$name\",";
  print OUT "\"$country\",";
  print OUT "$lati,";
  print OUT "$longt,";
  print OUT "\"$name\"";
  print OUT "},";
  print OUT "\n";
  }

print OUT "{NULL, NULL, 0, 0}";
print OUT "};\n";

